environment          = "prd"
aws_region           = "us-east-1"
instance_type        = "t3.large"
key_name             = "prd-boostlog-app-key"
domain_name          = "boostlog.app"
secret_name          = "boostlog/prd/secrets"
