name: Terraform Plan

on:
  pull_request:
    paths:
      - 'terraform/**'
      - 'terraform-trigger'

permissions:
  id-token: write      # Required for AWS OIDC
  contents: read       # Required for Checkout
  pull-requests: write # Required for commenting the plan on the PR

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: prd
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Inject GitHub Secrets into tfvars
        run: |
          echo "github_client_id = \"${{ secrets.GH_CLIENT_ID }}\"" >> environments/prd.tfvars
          echo "github_client_secret = \"${{ secrets.GH_CLIENT_SECRET }}\"" >> environments/prd.tfvars
          echo "cloudflare_tunnel_token = \"${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}\"" >> environments/prd.tfvars
          echo "db_password = \"${{ secrets.DB_PASSWORD }}\"" >> environments/prd.tfvars

      - name: Terraform Plan
        run: terraform plan -var-file="environments/prd.tfvars" -no-color
